---
- name: "installing npm"
  become: yes
  apt:
    name: npm
    update_cache: yes
    state: latest

# Opt to use nvm since to install node version 13.8.0
- name: Install nvm
  become: yes
  npm:
    name: n
    global: yes

- name: install nodejs v13.8.0
  become: yes
  command: n 13.8.0
# Install pm2
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present